--- 

  - name: Stopping httpd service
    systemd:
      state: stopped
      name: httpd
    when: ansible_os_family == "RedHat"  
    tags: apache 
  
  - name: disable httpd service
    systemd:
      name: httpd
      enabled: false
    when: ansible_os_family == "RedHat"  
    tags: apache 
 
  - name: Remove httpd
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"  
    tags: apache 
  
 
  - name: removing firewall rules http for httpd service
    firewalld:
      service: http
      permanent: true
      state: disabled
    notify: Reloading firewalld rules
    tags: apache 
  

  - name: removing firewall rules https for httpd service
    firewalld:
      service: https
      permanent: true
      state: disabled
    notify: Reloading firewalld rules
    tags: apache 
