---

- name: Install httpd  
  yum:
    name: httpd
  tags: apache


- name: Make sure httpd service is running and enabled
  systemd:
    state: started
    name: httpd
    enabled: yes
  tags: apache


- name: adding firewalld rules http for httpd
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
  tags: apache

- name: adding firewalld rules https for httpd
  firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled
  tags: apache


