---


- name: Install httpd  
  yum:
    name: httpd
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")
  tags: apache


- name: Install httpd  
  dnf:
    name: httpd
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  tags: apache


- name: Make sure httpd service is running and enabled
  systemd:
    state: started
    name: httpd
    enabled: yes
  tags: apache


- name: adding firewalld rules http for httpd
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
  tags: apache

- name: adding firewalld rules https for httpd
  firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled
  tags: apache


